version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.45.2
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/target.yml:/etc/prometheus/target.yml
      #- ./prometheus/data:/prometheus
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:10.2.3
    restart: always
    #volumes:
      #- ./grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: pa55ward  # please change it
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
