version: '3'

services:
  web:
    build:
      context: .
    command: "bash start.sh"
    env_file:
      - ./env/.env
    ports:
      - '8080:8080'
      - '8090:8090'
    networks:
      - prometheus-net

  jmx:
    build:
      context: .
      dockerfile: Dockerfile-with-jmx
    ports:
      - '8091:8091'
    environment:
      JAVA_OPTS: "-javaagent:/jmx_prometheus_javaagent-0.20.0.jar=8091:/prometheus-jmx-config.yaml"
    networks:
      - prometheus-net

  prometheus:
    image: prom/prometheus:v2.45.2
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/target.yml:/etc/prometheus/target.yml
      - ./prometheus/rule-up.yml:/etc/prometheus/rule-up.yml
      - ./prometheus/data:/prometheus
    ports:
      - '9090:9090'
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle" # enable reload api
    networks:
      - prometheus-net
    depends_on:
      - web
      - jmx
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.26.0
    restart: always
    ports:
      - '9093:9093'
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana:10.2.3
    restart: always
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: pa55ward  # please change it
    ports:
      - '3000:3000'
    networks:
      - prometheus-net
    depends_on:
      - prometheus


networks:
  prometheus-net:
