groups:
  - name: Test
    rules:
      - alert: InstanceUp
        expr: up{job="job_1"} == 1
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "{{ $labels.instance }}"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been up."
